# Generated by Django 3.1.5 on 2021-07-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pest_Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pestname', models.CharField(max_length=60)),
                ('pesttype', models.CharField(max_length=60)),
                ('tl', models.CharField(max_length=60)),
                ('tu', models.CharField(max_length=60)),
                ('dd', models.CharField(max_length=60)),
            ],
        ),
    ]
