# Generated by Django 3.1.5 on 2021-07-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pest_Management', '0002_pest_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pest_table',
            old_name='pestname',
            new_name='name',
        ),
    ]
